server:
  port: 8081


spring:
  application:
    name: shoppingSystem
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/shopping_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: my-secret-pw
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  bucketName: photos